#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ykclient
Version  : 2.15
Release  : 2
URL      : https://github.com/Yubico/yubico-c-client/archive/ykclient-2.15.tar.gz
Source0  : https://github.com/Yubico/yubico-c-client/archive/ykclient-2.15.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: ykclient-bin = %{version}-%{release}
Requires: ykclient-lib = %{version}-%{release}
Requires: ykclient-license = %{version}-%{release}
Requires: ykclient-man = %{version}-%{release}
BuildRequires : help2man
BuildRequires : pkgconfig(libcurl)
BuildRequires : valgrind
Patch1: 0001-Do-not-test-with-internet.patch

%description
== YubiKey C Client Library: libykclient ==
YubiKey C Client Library (libykclient) is a C library used to validate
an Yubikey OTP against Yubico's servers.  See
https://www.yubico.com[the Yubico website]
for more information about Yubico and the YubiKey.

%package bin
Summary: bin components for the ykclient package.
Group: Binaries
Requires: ykclient-license = %{version}-%{release}

%description bin
bin components for the ykclient package.


%package dev
Summary: dev components for the ykclient package.
Group: Development
Requires: ykclient-lib = %{version}-%{release}
Requires: ykclient-bin = %{version}-%{release}
Provides: ykclient-devel = %{version}-%{release}
Requires: ykclient = %{version}-%{release}

%description dev
dev components for the ykclient package.


%package lib
Summary: lib components for the ykclient package.
Group: Libraries
Requires: ykclient-license = %{version}-%{release}

%description lib
lib components for the ykclient package.


%package license
Summary: license components for the ykclient package.
Group: Default

%description license
license components for the ykclient package.


%package man
Summary: man components for the ykclient package.
Group: Default

%description man
man components for the ykclient package.


%prep
%setup -q -n yubico-c-client-ykclient-2.15
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571764412
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1571764412
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ykclient
cp COPYING %{buildroot}/usr/share/package-licenses/ykclient/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ykclient

%files dev
%defattr(-,root,root,-)
/usr/include/ykclient.h
/usr/include/ykclient_errors.h
/usr/include/ykclient_server_response.h
/usr/include/ykclient_version.h
/usr/lib64/libykclient.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libykclient.so.3
/usr/lib64/libykclient.so.3.6.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ykclient/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ykclient.1
